#!/usr/bin/env python3
"""Generate TypeScript types from the Python provider catalog.

This script generates a TypeScript file with:
- TestedProviderType: Union of tested provider IDs
- ProviderType: Union of all provider IDs
- PROVIDER_CATALOG: Static snapshot of catalog for offline/build-time use

Usage:
    python scripts/generate_provider_types.py
    python scripts/generate_provider_types.py --output frontend/src/types/generated-providers.ts
"""

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

# Add project root to path for imports
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from app.core.providers import PROVIDER_CATALOG, TESTED_PROVIDERS


def generate_typescript() -> str:
    """Generate TypeScript content from the Python catalog."""
    lines = [
        "// Auto-generated by scripts/generate_provider_types.py",
        f"// Generated at: {datetime.now(timezone.utc).isoformat()}",
        "// DO NOT EDIT MANUALLY - regenerate with: python scripts/generate_provider_types.py",
        "",
        "// Tested provider types (verified to work with ArgusLM)",
        "export type TestedProviderType =",
    ]

    # Generate tested provider union
    tested_sorted = sorted(TESTED_PROVIDERS)
    for i, provider_id in enumerate(tested_sorted):
        suffix = ";" if i == len(tested_sorted) - 1 else ""
        lines.append(f"  | '{provider_id}'{suffix}")

    lines.extend(
        [
            "",
            "// All provider types (includes untested providers from LiteLLM)",
            "export type AllProviderType =",
        ]
    )

    # Generate all provider union
    all_sorted = sorted(PROVIDER_CATALOG.keys())
    for i, provider_id in enumerate(all_sorted):
        suffix = ";" if i == len(all_sorted) - 1 else ""
        lines.append(f"  | '{provider_id}'{suffix}")

    lines.extend(
        [
            "",
            "// Provider specification interface",
            "export interface ProviderSpec {",
            "  id: string;",
            "  label: string;",
            "  tested: boolean;",
            "  requires_api_key: boolean;",
            "  requires_base_url: boolean;",
            "  requires_region: boolean;",
            "  show_org_fields: boolean;",
            "  default_base_url: string | null;",
            "  api_key_label: string | null;",
            "  base_url_label: string | null;",
            "  region_options: [string, string][];",
            "}",
            "",
            "// Static catalog snapshot (use API for runtime data)",
            "export const PROVIDER_CATALOG: Record<string, ProviderSpec> = {",
        ]
    )

    # Generate catalog entries
    for provider_id in all_sorted:
        spec = PROVIDER_CATALOG[provider_id]
        region_opts = ", ".join(f'["{code}", "{label}"]' for code, label in spec.region_options)
        lines.append(f"  '{provider_id}': {{")
        lines.append(f"    id: '{spec.id}',")
        lines.append(f"    label: '{spec.label}',")
        lines.append(f"    tested: {str(spec.tested).lower()},")
        lines.append(f"    requires_api_key: {str(spec.requires_api_key).lower()},")
        lines.append(f"    requires_base_url: {str(spec.requires_base_url).lower()},")
        lines.append(f"    requires_region: {str(spec.requires_region).lower()},")
        lines.append(f"    show_org_fields: {str(spec.show_org_fields).lower()},")
        lines.append(f"    default_base_url: {repr(spec.default_base_url)},")
        lines.append(f"    api_key_label: {repr(spec.api_key_label)},")
        lines.append(f"    base_url_label: {repr(spec.base_url_label)},")
        lines.append(f"    region_options: [{region_opts}],")
        lines.append("  },")

    lines.extend(
        [
            "};",
            "",
            "// Helper: Get list of tested provider IDs",
            f"export const TESTED_PROVIDER_IDS: TestedProviderType[] = {sorted(TESTED_PROVIDERS)};",
            "",
            "// Helper: Get list of all provider IDs",
            f"export const ALL_PROVIDER_IDS: AllProviderType[] = {all_sorted};",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate TypeScript types from Python provider catalog"
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=project_root / "frontend" / "src" / "types" / "generated-providers.ts",
        help="Output file path (default: frontend/src/types/generated-providers.ts)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print output to stdout instead of writing to file",
    )
    args = parser.parse_args()

    content = generate_typescript()

    if args.dry_run:
        print(content)
        print(f"\n# Would write to: {args.output}", file=sys.stderr)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content)
        print(f"Generated: {args.output}")
        print(f"  - {len(TESTED_PROVIDERS)} tested providers")
        print(f"  - {len(PROVIDER_CATALOG)} total providers")


if __name__ == "__main__":
    main()
